build:
  image: docker:19
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache bash
    - docker info
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
  script:
    - bash buildAndDeploy.sh php8-0.0.2
