workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

build:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: manual
  image: docker:19
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache bash
    - docker info
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
  script:
    - bash buildAndDeploy.sh ${CI_COMMIT_TAG-$IMAGE} $VERSION
